# Generated by Django 4.2.5 on 2026-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ingredients', models.JSONField(default=list)),
                ('directions', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
